import { Document, Schema, Model, model } from "mongoose";

/**
 * schema of a requirement template part
 * 
 */
export const RequirementTemplatePartSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        next: Schema.Types.ObjectId,
        version: Number,
        value: {}
    }
);