import { Document, Schema, Model, model } from "mongoose";

/**
 * schema of a relation between requirements
 * 
 */
export const RequirementRelationSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        requirementID: Schema.Types.ObjectId,
        type: Schema.Types.ObjectId,
        targetComponent: Schema.Types.ObjectId
    }
);