import { Document, Schema, Model, model } from "mongoose";
import { RequirementRelationSchema } from './requirement-relation.schema';
import { RequirementTemplatePartSchema } from './requirement-template-part.schema';
import { IRequirement } from "../interfaces/requirement.interface";

/**
 * interface represents requirements document which is stored in mongoDB
 * 
 */
export interface IRequirementModel extends IRequirement, Document {}

export const RequirementSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        version: Number,
        description: String,
        timestamp: Date,
        name: String,
        duration: Number,
        responsible: Schema.Types.ObjectId,
        category: Schema.Types.ObjectId,
        type: Schema.Types.ObjectId,
        stakeholder: Schema.Types.ObjectId,
        contractor: Schema.Types.ObjectId,
        dueDate: Date,
        status: Schema.Types.ObjectId,
        reason: {},
        descriptionParts: [RequirementTemplatePartSchema],
        relations: [RequirementRelationSchema],
        priority: Number,
        keyWords: String,
        acceptanceCriteria: String,
        descriptionTemplate: Schema.Types.ObjectId
    },
    {
        timestamps: true
    });


export const Requirement: Model<IRequirementModel> = model<IRequirementModel>("Requirement", RequirementSchema);