const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const requirementSchema = new Schema(
    {
        // _id is auto-generated by mongodb
        name: String,
        description: String,
        jsonModel: String
    }
);

const Requirement = mongoose.model('Requirement', requirementSchema);

module.exports = Requirement;