import { Schema, model } from 'mongoose';

/**
 * schema of a relation between requirements
 * 
 */
const RequirementRelationSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        requirementID: Schema.Types.ObjectId,
        type: Schema.Types.ObjectId,
        targetComponent: Schema.Types.ObjectId
    }
);

/**
 * schema of a requirement template part
 * 
 */
const RequirementTemplatePartSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        next: Schema.Types.ObjectId,
        version: Number,
        value: {}
    }
);

/**
 * requirement schema
 * 
 */
const RequirementSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        version: Number,
        description: String,
        timestamp: Date,
        name: String,
        duration: Number,
        responsible: Schema.Types.ObjectId,
        category: Schema.Types.ObjectId,
        type: Schema.Types.ObjectId,
        stakeholder: Schema.Types.ObjectId,
        contractor: Schema.Types.ObjectId,
        dueDate: Date,
        status: Schema.Types.ObjectId,
        reason: {},
        descriptionParts: [RequirementTemplatePartSchema],
        relations: [RequirementRelationSchema],
        priority: Number,
        keyWords: String,
        acceptanceCriteria: String,
        descriptionTemplate: Schema.Types.ObjectId
    },
    {
        timestamps: true
    }
);

/**
 * create requirement model and export model
 * 
 */
export const Requirement = model('Requirement', RequirementSchema);