import { Schema, model } from 'mongoose';

/**
 * schema of a relation between requirements
 * 
 */
const RequirementRelationSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        componentID: Schema.Types.ObjectId,
        type: {
            type: String,
            enum: [
                'leitet ab',
                'ist abhängig von',
                'enthält',
                'schränkt ein',
                'erweitert',
                'steht in Konflikt zu'
                // ToDo: complete list
            ]
        },
        targetComponentID: Schema.Types.ObjectId
    },
    {
        timestamps: true
    }
);

/**
 * create requirement relation model and export model
 * 
 */
export const RequirementRelation = model('RequirementRelation', RequirementRelationSchema);