import { Schema, model } from 'mongoose';

/**
 * schema of a relation between requirements
 * 
 */
const RequirementRelationSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        requirementID: Schema.Types.ObjectId,
        type: Schema.Types.ObjectId,
        targetComponent: Schema.Types.ObjectId
    }
);

/**
 * schema of a requirement template part
 * 
 */
const RequirementTemplatePartSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        next: Schema.Types.ObjectId,
        version: Number,
        value: {}
    }
);

/**
 * requirement schema
 * 
 */
const RequirementSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        version: Number,
        description: String,      
        name: String,
        duration: Number,
        responsible: String,
        category: {
            type: String,
            enum: [
                'Geschäftliche Anforderungen',
                'Normen und Gesetze',
                'Produkteigenschaften',
                'Anforderungen an den Produktlebenszyklus',
                'Designanforderungen'
            ]
        },
        type: {
            type: String,
            enum: [
                'FA',
                'NFA'
            ]
        },
        stakeholder: String,
        contractor: String,
        dueDate: Date,
        status: {
            type: String,
            enum: [
                'Maßnahme festgelegt',
                'Ablauf defniert',
                'Maßnahmenbearbeitung gestartet',
                'Maßnahme umgesetzt',
                'Maßnahme abgeschlossen'
            ]
        },
        reason: {},
        descriptionParts: [RequirementTemplatePartSchema],
        relations: [RequirementRelationSchema],
        priority: {
            type: String,
            enum: [
                'Must-have',
                'Should-have',
                'Nice-to-have',
                'Soon-to-be'
            ]
        },
        keyWords: [String],
        acceptanceCriteria: String,

        // ToDo write method which compares description template with given description parts
        descriptionTemplate: Schema.Types.ObjectId
    },
    {
        timestamps: true
    }
);

/**
 * create requirement model and export model
 * 
 */
export const Requirement = model('Requirement', RequirementSchema);