import { Schema, model } from 'mongoose';

/**
 * schema of a requirement template part
 * 
 */
const RequirementTemplatePartSchema: Schema = new Schema(
    {
        // _id is auto-generated by mongodb
        next: Schema.Types.ObjectId,
        version: Number,
        value: {},
        type: {
            type: String,
            enum: [
                'dropdown',
                'input',
                'text',
                'table',
                'wrapper'
                // ToDo: complete list
            ]
        },
        head: Boolean
    }
);

/**
 * create requirement template part model and export model
 * 
 */
export const RequirementTemplatePart = model('RequirementTemplatePart', RequirementTemplatePartSchema);