const mongoose = require('mongoose');

const Schema = mongoose.Schema;

// import mongoose data types
const ObjectId = Schema.ObjectId;

const requirementTemplatePartSchema = new Schema(
    {
        // _id is auto-generated by mongodb
        next: ObjectId,
        version: Number,
        value: {}
    }
);

module.exports = requirementTemplatePartSchema;