const mongoose = require('mongoose');

const Schema = mongoose.Schema;

// import mongoose data types
const ObjectId = Schema.ObjectId;

const requirementRelationSchema = new Schema(
    {
        // _id is auto-generated by mongodb
        requirementID: ObjectId,
        type: ObjectId,
        targetComponent: ObjectId
    }
);

module.exports = requirementRelationSchema;