const mongoose = require('mongoose');
const requirementTemplatePartSchema = require('./requirementTemplatePart.schema');
const requirementRelationSchema = require('./requirementRelation.schema');

const Schema = mongoose.Schema;

// import mongoose data types
const ObjectId = Schema.ObjectId;

const requirementSchema = new Schema(
    {
        // _id is auto-generated by mongodb
        version: Number,
        description: String,
        timestamp: Date,
        name: String,
        duration: Number,
        responsible: ObjectId,
        category: ObjectId,
        type: ObjectId,
        stakeholder: ObjectId,
        contractor: ObjectId,
        dueDate: Date,
        status: ObjectId,
        reason: {},
        descriptionParts: [requirementTemplatePartSchema],
        relations: [requirementRelationSchema],
        priority: Number,
        keyWords: String,
        acceptanceCriteria: String,
        descriptionTemplate: ObjectId
    }
);

const Requirement = mongoose.model('Requirement', requirementSchema);

module.exports = Requirement;