const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const requirementRelationSchema = new Schema(
    {
        // _id is auto-generated by mongodb

    }
);

module.exports = requirementRelationSchema;